# app/integrations/stripe/types/refund/models.py

"""Response schema for the Stripe Refund object.

Translated field-for-field from the Stripe API reference; descriptions verbatim.
API Reference: https://docs.stripe.com/api/refunds/object
"""

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class RefundStatus(str, Enum):
    """Status of the refund.

    See https://docs.stripe.com/refunds#see-also for the lifecycle. For card
    refunds this is `pending`, then `succeeded` or `failed`; `requires_action`
    covers refunds needing additional steps; `canceled` covers refunds cancelled
    before completion.
    """

    PENDING = "pending"
    REQUIRES_ACTION = "requires_action"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    CANCELED = "canceled"


class Refund(BaseModel):
    """A Refund object. Funds are refunded to the customer's original payment method."""

    model_config = ConfigDict(extra="allow")

    id: str = Field(..., description="Unique identifier for the object.")
    object: str = Field(
        "refund",
        description="String representing the object's type. Objects of the same type share the same value.",
    )
    amount: int = Field(..., description="Amount, in cents (or local equivalent).")
    charge: Optional[str] = Field(
        None, description="ID of the charge that was refunded."
    )
    currency: str = Field(
        ..., description="Three-letter ISO currency code, in lowercase. Must be a supported currency."
    )
    created: int = Field(
        ..., description="Time at which the object was created. Measured in seconds since the Unix epoch."
    )
    payment_intent: Optional[str] = Field(
        None, description="ID of the PaymentIntent that was refunded."
    )
    reason: Optional[str] = Field(
        None,
        description=(
            "Reason for the refund, either user-provided (`duplicate`, `fraudulent`, or "
            "`requested_by_customer`) or generated by Stripe internally (`expired_uncaptured_charge`)."
        ),
    )
    receipt_number: Optional[str] = Field(
        None,
        description="This is the transaction number that appears on email receipts sent for this refund.",
    )
    status: Optional[RefundStatus] = Field(
        None,
        description=(
            "Status of the refund. This can be `pending`, `requires_action`, `succeeded`, "
            "`failed`, or `canceled`."
        ),
    )
    failure_reason: Optional[str] = Field(
        None,
        description=(
            "Provides the reason for the refund failure. Possible values are: `lost_or_stolen_card`, "
            "`expired_or_canceled_card`, `charge_for_pending_refund_disputed`, `insufficient_funds`, "
            "`declined`, `merchant_request`, or `unknown`."
        ),
    )
